### ISSUE TITLE
Click the head time to enter the the details bug

### ISSUE THREAD

**Issue by mfkwgizhoujian** [ANovokmet/svelte-gantt#66] opened 2022-04-14 12:22 UTC
After clicking the head time to enter the details, you can no longer return to the current view. You can only enter the later time details.
Step 1. Click '15.04.2022'
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/33543763/163388755-fd6f4dbd-6293-470b-89d6-8a226d7d0eb9.png">
Step 2. Click the blank space in the box, can enter the details '16.04.2022'
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/33543763/163388948-6ccb0269-8fff-46a7-befd-a85fc22f16b6.png">
Step 3. How can I return to '14.04.2022'?

**Comment by V-Py** [comment] 2022-06-04 06:50
Hi, it seems to me **you're trying to navigate over time using only the header** of the Svelte Gantt.
I don't think if it was designed to be used that way, but more for a zoom-in/zoom-out usage.

In all the projects where I'm using Svelte Gantt, I implemented navigation buttons such as 
![image](https://user-images.githubusercontent.com/59333024/171988178-fc6f8fef-a4f9-4b16-a84f-ccc0abd2d237.png)

Could you confirm that your problem is indeed only a navigation with header problem so I can close this issue please 😄  ?

**Comment by V-Py** [comment] 2022-06-13 09:32
Hi @mfkwgizhoujian, I'm sorry but it definitely looks like this isn't a real problem but a problem of usage.
And since you didn't respond to my message, I'll close this issue until further notice. 
Let me know if I didn't understand your issue correctly and if this one needs to be reopened 😃

**Closed as completed by V-Py** 2022-06-13 09:32 UTC
Labels: bug
