### ISSUE TITLE
rowHeight  can't update

### ISSUE THREAD

**Issue by zhaofang** [ANovokmet/svelte-gantt#47] opened 2021-11-30 03:04 UTC
window.onresize, use gantt.$set({rowHeight: 50}), unchanged

**Comment by zhaofang** [comment] 2021-11-30 07:38
let newRowsWithHeight = rows.map(r => ({id: r.id, height: retHeight}))
  gantt.$set({
    rowHeight: getRowHeight(),
    rows: newRowsWithHeight
})
fix it, need update rowHeight and rows

**Comment by V-Py** [comment] 2022-05-03 05:34
Hello, I **can't reproduce your issue**, I'm having 0 problem resizing the rows using `gantt.$set({rowHeight: 50})` (or any other random number). 
The only issue I encountered was the tasks inside rows not resizing too, but you might have to programmatically change it yourself for now.
Could you **explain it a bit more** or give access to the code so I can understand what your problem is ?

**Comment by V-Py** [comment] 2022-06-04 06:44
Hey @zhaofang, would you mind answering to my post please 😄 ? 
I'm trying to see which issues are still standing and since I already investigated your problem, I would like some more details so I can solve it or close it !
Thanks

**Comment by V-Py** [comment] 2022-06-13 09:37
Hi @zhaofang, since you didn't answer to my previous posts, and I wasn't able to reproduce your issue, I'll close this one until further notice.
Don't hesitate to let me know if I understood it wrong, and if it needs to be reopened 😃

**Closed as completed by V-Py** 2022-06-13 09:37 UTC
Labels: bug
